version: '3'
services:
  db:
    build:
      context: ../
      dockerfile: .docker/mysql/Dockerfile
    restart: always

  php:
    image: prestashop/prestashop:1.7.7.5-apache
    ports:
      - "80:80"
    volumes:
      - ../public_html:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: